In [9]:
from PIL import Image
path='/home/user/rashmi/images/sun.jpg'
image=Image.open(path)
width=image.width
height=image.height
print('image width',width)
print('image height',height)

image width 193
image height 261


In [ ]:
import cv2
import numpy
img = cv2.imread("/home/user/rashmi/images/sun.jpg")
print('No of Channel is: ' + str(img.ndim))
cv2.imshow("Channel", img)
cv2.waitKey()
cv2.destroyAllWindows()

No of Channel is: 3


In [4]:
import cv2
img=cv2.imread('/home/user/rashmi/images/face.jpg')
B,G,R=cv2.split(img)
print(B)
print(G)
print(R)

[[154 154 154 ... 151 151 151]
 [154 154 154 ... 151 151 151]
 [154 154 154 ... 151 151 151]
 ...
 [  1   1   1 ...   6   6   6]
 [  1   1   1 ...   6   6   6]
 [ 26  26  26 ...  18  18  18]]
[[166 166 166 ... 163 163 163]
 [166 166 166 ... 163 163 163]
 [166 166 166 ... 163 163 163]
 ...
 [  3   3   3 ...   7   7   7]
 [  3   3   3 ...   7   7   7]
 [ 28  28  28 ...  20  20  20]]
[[160 160 160 ... 157 157 157]
 [160 160 160 ... 157 157 157]
 [160 160 160 ... 157 157 157]
 ...
 [  3   3   3 ...   5   5   5]
 [  3   3   3 ...   3   3   3]
 [ 28  28  28 ...  14  14  14]]


In [ ]:
import cv2
img=cv2.imread('/home/user/rashmi/images/face.jpg')
B,G,R=cv2.split(img)
print(B)
print(G)
print(R)
cv2.imshow("green",B)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[154 154 154 ... 151 151 151]
 [154 154 154 ... 151 151 151]
 [154 154 154 ... 151 151 151]
 ...
 [  1   1   1 ...   6   6   6]
 [  1   1   1 ...   6   6   6]
 [ 26  26  26 ...  18  18  18]]
[[166 166 166 ... 163 163 163]
 [166 166 166 ... 163 163 163]
 [166 166 166 ... 163 163 163]
 ...
 [  3   3   3 ...   7   7   7]
 [  3   3   3 ...   7   7   7]
 [ 28  28  28 ...  20  20  20]]
[[160 160 160 ... 157 157 157]
 [160 160 160 ... 157 157 157]
 [160 160 160 ... 157 157 157]
 ...
 [  3   3   3 ...   5   5   5]
 [  3   3   3 ...   3   3   3]
 [ 28  28  28 ...  14  14  14]]


In [ ]:
import cv2
img=cv2.imread('/home/user/rashmi/images/face.jpg')
B,G,R=cv2.split(img)
print(B)
print(G)
print(R)
cv2.imshow("blue",B)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[154 154 154 ... 151 151 151]
 [154 154 154 ... 151 151 151]
 [154 154 154 ... 151 151 151]
 ...
 [  1   1   1 ...   6   6   6]
 [  1   1   1 ...   6   6   6]
 [ 26  26  26 ...  18  18  18]]
[[166 166 166 ... 163 163 163]
 [166 166 166 ... 163 163 163]
 [166 166 166 ... 163 163 163]
 ...
 [  3   3   3 ...   7   7   7]
 [  3   3   3 ...   7   7   7]
 [ 28  28  28 ...  20  20  20]]
[[160 160 160 ... 157 157 157]
 [160 160 160 ... 157 157 157]
 [160 160 160 ... 157 157 157]
 ...
 [  3   3   3 ...   5   5   5]
 [  3   3   3 ...   3   3   3]
 [ 28  28  28 ...  14  14  14]]
